const { SlashCommandBuilder, EmbedBuilder, PermissionFlagsBits } = require('discord.js');
const axios = require('axios');

// Free unlimited AI using Pollinations
async function generateAIJoke(targetUser = null, type = 'general') {
  try {
    const prompts = {
      general: "Tell me a funny joke. Keep it under 150 characters.",
      roast: targetUser ? `Roast user ${targetUser} with a funny but light-hearted joke. Keep it under 150 characters.` : "Tell me a funny roast joke. Keep it under 150 characters.",
      pun: "Tell me a clever pun. Keep it under 150 characters."
    };

    const response = await axios.get(`https://text.pollinations.ai/${encodeURIComponent(prompts[type])}?seed=${Date.now()}&json=false`, {
      timeout: 5000
    });
    
    return response.data || "Why did the chicken cross the road? To get to the other side!";
  } catch (error) {
    console.error('AI Joke Error:', error.message);
    // Fallback jokes
    const fallbackJokes = [
      "Why don't scientists trust atoms? Because they make up everything!",
      "Why did the scarecrow win an award? He was outstanding in his field!",
      "What do you call a fake noodle? An impasta!"
    ];
    return fallbackJokes[Math.floor(Math.random() * fallbackJokes.length)];
  }
}

module.exports = {
  data: new SlashCommandBuilder()
    .setName('joke')
    .setDescription('Get an AI-generated joke')
    .addStringOption(option =>
      option
        .setName('type')
        .setDescription('Type of joke')
        .setRequired(false)
        .addChoices(
          { name: 'General', value: 'general' },
          { name: 'Roast', value: 'roast' },
          { name: 'Pun', value: 'pun' }
        ))
    .addUserOption(option =>
      option
        .setName('target')
        .setDescription('Target user for roast (optional)')
        .setRequired(false))
    .addStringOption(option =>
      option
        .setName('delivery')
        .setDescription('How to deliver the joke')
        .setRequired(false)
        .addChoices(
          { name: 'Just me', value: 'personal' },
          { name: 'Mention everyone', value: 'everyone' }
        )),

  async execute(interaction) {
    await interaction.deferReply();
    
    const type = interaction.options.getString('type') || 'general';
    const targetUser = interaction.options.getUser('target');
    const delivery = interaction.options.getString('delivery') || 'personal';

    if (delivery === 'everyone' && !interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {
      return interaction.editReply('❌ Only admins can mention everyone!');
    }

    const joke = await generateAIJoke(targetUser?.username, type);

    const embed = new EmbedBuilder()
      .setTitle(type === 'roast' ? '🔥 AI Roast!' : type === 'pun' ? '😄 AI Pun!' : '🤣 AI Joke!')
      .setDescription(`**${joke}**`)
      .setColor(0xFFD700)
      .setFooter({ text: 'Generated by AI • Toolmetry AI Bot' })
      .setTimestamp();

    if (targetUser && type === 'roast') {
      embed.setDescription(`${targetUser} **${joke}**`);
    }

    if (delivery === 'everyone') {
      await interaction.deleteReply();
      await interaction.channel.send({ content: '@everyone', embeds: [embed] });
    } else {
      await interaction.editReply({ embeds: [embed] });
    }
  }
};

module.exports.generateAIJoke = generateAIJoke;
